theme: jekyll-theme-caymane
#show_downloads: true
#github:
#  zip_url: https://github.com/marvin-mangold/S7-PLC_MySql_MariaDB/zipball/master
#  tar_url: https://github.com/marvin-mangold/S7-PLC_MySql_MariaDB/tarball/master
